version: '3.8'
volumes:
  - /var/run/docker.sock:/var/run/docker.sock
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    image: flask-devops-realworld
    container_name: flask-devops-realworld

